name: sccache
base: core18
type: app
adopt-info: sccache

summary: sccache is ccache with cloud storage
description: |
    sccache is a ccache-like tool. It is used as a compiler wrapper and avoids
    compilation when possible, storing a cache in a remote storage using the
    Amazon Simple Cloud Storage Service (S3) API, the Google Cloud Storage (GCS)
    API, or Redis.

grade: stable
confinement: classic

apps:
    sccache:
        command: bin/sccache.wrapper

    sccache-server:
        environment:
            SCCACHE_START_SERVER: 1
            SCCACHE_NO_DAEMON: 1
            SCCACHE_IDLE_TIMEOUT: 0
        command: bin/sccache.wrapper
        daemon: simple
        passthrough:
            daemon-scope: user

parts:
    sccache:
        plugin: rust
        source: .
        source-type: git
        build-packages:
        - libssl-dev
        - make
        - pkg-config
        rust-features:
        - gcs
        - redis
        - s3
        override-pull: |
            snapcraftctl pull
            snapcraftctl set-version "$(git describe --tags)"

    wrapper:
        plugin: dump
        source: snap
        prime: [bin]
